/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CurrencyReport {
    }
    interface HackernewsJobs {
    }
}
declare global {
    interface HTMLCurrencyReportElement extends Components.CurrencyReport, HTMLStencilElement {
    }
    var HTMLCurrencyReportElement: {
        prototype: HTMLCurrencyReportElement;
        new (): HTMLCurrencyReportElement;
    };
    interface HTMLHackernewsJobsElement extends Components.HackernewsJobs, HTMLStencilElement {
    }
    var HTMLHackernewsJobsElement: {
        prototype: HTMLHackernewsJobsElement;
        new (): HTMLHackernewsJobsElement;
    };
    interface HTMLElementTagNameMap {
        "currency-report": HTMLCurrencyReportElement;
        "hackernews-jobs": HTMLHackernewsJobsElement;
    }
}
declare namespace LocalJSX {
    interface CurrencyReport {
    }
    interface HackernewsJobs {
    }
    interface IntrinsicElements {
        "currency-report": CurrencyReport;
        "hackernews-jobs": HackernewsJobs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "currency-report": LocalJSX.CurrencyReport & JSXBase.HTMLAttributes<HTMLCurrencyReportElement>;
            "hackernews-jobs": LocalJSX.HackernewsJobs & JSXBase.HTMLAttributes<HTMLHackernewsJobsElement>;
        }
    }
}
